### ISSUE TITLE
【BUG】疑似触发连续对话时会在所有已加入的群同时触发连续对话

### ISSUE THREAD

**Issue by KaRuiqin** [LaoLittle/Molly#10]
如题，当bot在某一个群被触发的同时在所有已加入的群都会对说话群友的消息进行回复。
好像是从之前修复引用消息异常的那个版本开始有的

**Comment by LaoLittle** [comment]
使用 [1.4.0](https://github.com/LaoLittle/Molly/releases/tag/1.4.0)

**Comment by KaRuichin** [comment]
好哦
