### ISSUE TITLE
使Bot不对图片消息进行回复

### ISSUE THREAD

**Issue by Achley-233** [LaoLittle/Molly#2]
这个接口对图片消息返回的回复似乎不太理想，我尝试在不触发聊天关键词中加入`mirai:image`但似乎不起作用。
![image](https://user-images.githubusercontent.com/69111766/152929633-63f594b9-122b-482b-9912-4da79dcc5843.png)
请求加入新的可选功能使使Bot不对图片消息进行回复。

**Comment by LaoLittle** [comment]
图片会以纯文本（[图片]或[动画表情]）形式上传至服务器，你可以自定义回复

**Comment by Achley-233** [comment]
明白了，感谢您的回复 >_<

**Comment by Achley-233** [comment]
不过还是无法屏蔽对图片消息的触发的话对其他插件处理消息还是有点影响，还是希望大佬如果有空的话整一个()

**Comment by LaoLittle** [comment]
> 不过还是无法屏蔽对图片消息的触发的话对其他插件处理消息还是有点影响，还是希望大佬如果有空的话整一个()

其实我觉得可以直接把配置文件的那个屏蔽关键字稍微拓展一下，改成全局生效，然后加入屏蔽[图片]就行了
