### ISSUE TITLE
[BUG]连续对话引用回复消息不正确

### ISSUE THREAD

**Issue by Achley-233** [LaoLittle/Molly#4]
![%M7IB)4T9~B 74QD89YMT6O](https://user-images.githubusercontent.com/69111766/176190974-dc32816a-e921-4b75-b551-5bf74eb1c160.png)
而不是（如图）引用该连续对话的第一条消息。

**Comment by LaoLittle** [comment]
这是一个bug，等待修复

**Comment by LaoLittle** [comment]
https://github.com/LaoLittle/Molly/releases/tag/1.3.1

**Comment by Achley-233** [comment]
> https://github.com/LaoLittle/Molly/releases/tag/1.3.1

好耶，谢谢大佬
